version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PROD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PROD_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROD_POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always

  backend:
    build: .
    restart: always
    ports:
      - "127.0.0.1:5000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=${PROD_DATABASE_URL}
      - REDIS_URL=${PROD_REDIS_URL}
    depends_on:
      - postgres
      - redis
    volumes:
      - whatsapp_session:/app/.wwebjs_auth
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "127.0.0.1:3000:80"
    environment:
      - VITE_API_URL=${PROD_VITE_API_URL}
    depends_on:
      - backend

volumes:
  pgdata:
  whatsapp_session: